exports.config={
    framework:'jasmine',
    directConnect:true,
    specs:['spec.js'],
    capabilities:{
        browserName:'chrome'
    },
    onPrepare(){
        browser.ignoreSynchronization=true;
    }
}